// <auto-generated />
using MVCHOT2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCHOT2.Migrations
{
    [DbContext(typeof(TestProductContext))]
    [Migration("20240205231324_Migration02-Category")]
    partial class Migration02Category
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCHOT2.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "ACC",
                            CategoryName = "Accessories"
                        },
                        new
                        {
                            CategoryId = "BIK",
                            CategoryName = "Bikes"
                        },
                        new
                        {
                            CategoryId = "CLO",
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = "COM",
                            CategoryName = "Components"
                        },
                        new
                        {
                            CategoryId = "CAR",
                            CategoryName = "Car racks"
                        },
                        new
                        {
                            CategoryId = "WHE",
                            CategoryName = "Wheels"
                        });
                });

            modelBuilder.Entity("MVCHOT2.Models.TestProduct", b =>
                {
                    b.Property<int>("TestProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestProductId"));

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductDescLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("TestProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("TestProducts");

                    b.HasData(
                        new
                        {
                            TestProductId = 1,
                            CategoryId = "COM",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "AeroFlo ATB Wheels",
                            ProductPrice = 189.0,
                            ProductQuantity = 40
                        },
                        new
                        {
                            TestProductId = 2,
                            CategoryId = "ACC",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "Clear Shade 85-T Glasses",
                            ProductPrice = 45.0,
                            ProductQuantity = 14
                        },
                        new
                        {
                            TestProductId = 3,
                            CategoryId = "COM",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "Cosmic Elite Road Warrior Wheels",
                            ProductPrice = 165.0,
                            ProductQuantity = 22
                        },
                        new
                        {
                            TestProductId = 4,
                            CategoryId = "ACC",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "Cycle-Doc Pro Repair Stand",
                            ProductPrice = 166.0,
                            ProductQuantity = 12
                        },
                        new
                        {
                            TestProductId = 5,
                            CategoryId = "ACC",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "Dog Ear Aero-Flow Floor Pump",
                            ProductPrice = 5.0,
                            ProductQuantity = 25
                        },
                        new
                        {
                            TestProductId = 6,
                            CategoryId = "ACC",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "Dog Ear Cycle Computer",
                            ProductPrice = 75.0,
                            ProductQuantity = 20
                        },
                        new
                        {
                            TestProductId = 7,
                            CategoryId = "ACC",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "Dog Ear Helmet Mount Mirrors",
                            ProductPrice = 7.4500000000000002,
                            ProductQuantity = 12
                        },
                        new
                        {
                            TestProductId = 8,
                            CategoryId = "ACC",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "Dog Ear Monster Grip Gloves",
                            ProductPrice = 15.0,
                            ProductQuantity = 30
                        },
                        new
                        {
                            TestProductId = 9,
                            CategoryId = "BIK",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "Eagle FS-3 Mountain Bike",
                            ProductPrice = 1800.0,
                            ProductQuantity = 8
                        },
                        new
                        {
                            TestProductId = 10,
                            CategoryId = "COM",
                            ProductDescLong = "",
                            ProductDescShort = " ",
                            ProductImage = "",
                            ProductName = "Eagle SA-120 Clipless Pedals",
                            ProductPrice = 139.94999999999999,
                            ProductQuantity = 20
                        });
                });

            modelBuilder.Entity("MVCHOT2.Models.TestProduct", b =>
                {
                    b.HasOne("MVCHOT2.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
